// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.8.0.0")]
[assembly: AssemblyFileVersionAttribute("1.8.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.8.0")]
[assembly: AssemblyProductAttribute("HuntAndPeck")]
[assembly: AssemblyCopyrightAttribute("Copyright Zachary Sims")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.8.0.0";
    }
}
